name: dlog

on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Build
        run: |
          go run ./cmd/dlog \
          --source docs \
          --build .. \
          --sitename "dlog" \
          --sidebar=false \
          --html=true \
          --sitemap.domain=dlog.emadelsaid.com \
          --rss.domain dlog.emadelsaid.com \
          --activitypub.domain=dlog.emadelsaid.com \
          --activitypub.username=app \
          --activitypub.summary="dlog is a static site generator for digital gardening written in Go. It serves markdown files as HTML and allows editing files online. It focuses on enriching markdown files and surfacing implicit links between pages." \
          --og.domain dlog.emadelsaid.com \
          --github.url https://github.com/m4salah/dlog/edit/master/docs
          mv docs/* .
          rm *.md
          chmod -R 0777 .

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
